enum ExpenseCategory {
  RENT = 'RENT',
  UTILITIES = 'UTILITIES',
  SALARIES = 'SALARIES',
  WAYBILLFEES = 'WAYBILLFEES',
  MAINTENANCE = 'MAINTENANCE',
  MISCELLANEOUS = 'MISCELLANEOUS',
  FEEDING = 'FEEDING',
  DAILY_TRANSPORT = 'DAILY_TRANSPORT',
  WORKERS_PAYMENT = 'WORKERS_PAYMENT',
}

export default ExpenseCategory;
