enum ExpenseCategory {
  RENT = 'RENT',
  UTILITIES = 'UTILITIES',
  SALARIES = 'SALARIES',
  WAY_BILLFEES = 'WAY_BILLFEES',
  MAINTENANCE = 'MAINTENANCE',
  MISCELLANEOUS = 'MISCELLANEOUS',
  FEEDING = 'FEEDING',
  DAILY_TRANSPORT = 'DAILY_TRANSPORT',
  WORKES_PAYMENT = 'WORKES_PAYMENT',
}

export default ExpenseCategory;
