import { Injectable } from '@nestjs/common';
import ProductVariantRepository from '../repositories/product/product-variant.repository';
import ProductVariant from 'src/domain/product/product-variant';
import { ActorType } from 'src/domain/common/actor-type';

@Injectable()
export class ProductVariantSeed {
  constructor(
    private readonly variants: ProductVariantRepository,
  ) {}

  async seed() {
    const existingVariants: ProductVariant[] = await this.variants.findAll();

    if (existingVariants.length > 0) {
      console.log('Product variants already exist. Skipping seed.');
      return;
    }

    // Product IDs based on seeding order:
    // 1. Bridgestone Turanza T005
    // 2. Presa PS01
    // 3. Maxxis MA-P3
    // 4. Michelin Primacy 4
    // 5. Bridgestone Dueler H/T
    // 6. Maxxis AT-771 Bravo
    // 7. Austone Tricycle Tyre
    // 8. Hifly Keke NAPEP Tyre
    // 9. Firestone Performer
    // 10. Dunlop Farm Pro
    // 11. Bridgestone Duravis
    // 12. Seeman Standard
    // 13. Varta Blue Dynamic
    // 14. Bosch S4
    // 15. Solite Silver
    // 16. Seeman Heavy Duty
    // 17. Varta Promotive Black
    // 18. Solite Bike
    // 19. Sachs Shock Absorber
    // 20. Monroe OESpectrum
    // 21. TRW Tie Rod End
    // 22. Lemforder Ball Joint
    // 23. TRW Steering Rack End
    // 24. TRW Brake Pad

    const defaultVariants = [
      // Product 1: Bridgestone Turanza T005 - Car Tyres
      {
        id: undefined,
        productId: 1,
        sku: 'BRI-T005-195-65-15',
        variantName: '195/65 R15',
        price: 45000,
        specifications: {
          width: 195,
          aspectRatio: 65,
          rimSize: 15,
          loadIndex: 91,
          speedRating: 'H',
          pattern: 'Symmetric',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 1,
        sku: 'BRI-T005-205-55-16',
        variantName: '205/55 R16',
        price: 52000,
        specifications: {
          width: 205,
          aspectRatio: 55,
          rimSize: 16,
          loadIndex: 91,
          speedRating: 'V',
          pattern: 'Symmetric',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 1,
        sku: 'BRI-T005-225-45-17',
        variantName: '225/45 R17',
        price: 62000,
        specifications: {
          width: 225,
          aspectRatio: 45,
          rimSize: 17,
          loadIndex: 94,
          speedRating: 'W',
          pattern: 'Symmetric',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 2: Presa PS01 - Car Tyres
      {
        id: undefined,
        productId: 2,
        sku: 'PRE-PS01-175-70-13',
        variantName: '175/70 R13',
        price: 18000,
        specifications: {
          width: 175,
          aspectRatio: 70,
          rimSize: 13,
          loadIndex: 82,
          speedRating: 'T',
          pattern: 'Symmetric',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 2,
        sku: 'PRE-PS01-185-65-14',
        variantName: '185/65 R14',
        price: 22000,
        specifications: {
          width: 185,
          aspectRatio: 65,
          rimSize: 14,
          loadIndex: 86,
          speedRating: 'T',
          pattern: 'Symmetric',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 2,
        sku: 'PRE-PS01-195-65-15',
        variantName: '195/65 R15',
        price: 25000,
        specifications: {
          width: 195,
          aspectRatio: 65,
          rimSize: 15,
          loadIndex: 91,
          speedRating: 'H',
          pattern: 'Symmetric',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 3: Maxxis MA-P3 - Car Tyres
      {
        id: undefined,
        productId: 3,
        sku: 'MAX-MAP3-185-70-14',
        variantName: '185/70 R14',
        price: 28000,
        specifications: {
          width: 185,
          aspectRatio: 70,
          rimSize: 14,
          loadIndex: 88,
          speedRating: 'H',
          pattern: 'Symmetric',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 3,
        sku: 'MAX-MAP3-195-60-15',
        variantName: '195/60 R15',
        price: 32000,
        specifications: {
          width: 195,
          aspectRatio: 60,
          rimSize: 15,
          loadIndex: 88,
          speedRating: 'H',
          pattern: 'Symmetric',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 4: Michelin Primacy 4 - Car Tyres
      {
        id: undefined,
        productId: 4,
        sku: 'MIC-PRI4-205-55-16',
        variantName: '205/55 R16',
        price: 65000,
        specifications: {
          width: 205,
          aspectRatio: 55,
          rimSize: 16,
          loadIndex: 91,
          speedRating: 'V',
          pattern: 'Asymmetric',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 4,
        sku: 'MIC-PRI4-225-45-17',
        variantName: '225/45 R17',
        price: 75000,
        specifications: {
          width: 225,
          aspectRatio: 45,
          rimSize: 17,
          loadIndex: 94,
          speedRating: 'W',
          pattern: 'Asymmetric',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 5: Bridgestone Dueler H/T - SUV Tyres
      {
        id: undefined,
        productId: 5,
        sku: 'BRI-DHT-225-65-17',
        variantName: '225/65 R17',
        price: 68000,
        specifications: {
          width: 225,
          aspectRatio: 65,
          rimSize: 17,
          loadIndex: 102,
          speedRating: 'H',
          pattern: 'Symmetric',
          vehicleType: 'SUV',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 5,
        sku: 'BRI-DHT-265-65-17',
        variantName: '265/65 R17',
        price: 82000,
        specifications: {
          width: 265,
          aspectRatio: 65,
          rimSize: 17,
          loadIndex: 112,
          speedRating: 'H',
          pattern: 'Symmetric',
          vehicleType: 'SUV',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 6: Maxxis AT-771 Bravo - SUV Tyres
      {
        id: undefined,
        productId: 6,
        sku: 'MAX-AT771-265-70-16',
        variantName: '265/70 R16',
        price: 55000,
        specifications: {
          width: 265,
          aspectRatio: 70,
          rimSize: 16,
          loadIndex: 112,
          speedRating: 'S',
          pattern: 'All-Terrain',
          vehicleType: '4x4',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 6,
        sku: 'MAX-AT771-235-75-15',
        variantName: '235/75 R15',
        price: 48000,
        specifications: {
          width: 235,
          aspectRatio: 75,
          rimSize: 15,
          loadIndex: 109,
          speedRating: 'S',
          pattern: 'All-Terrain',
          vehicleType: '4x4',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 7: Austone Tricycle Tyre
      {
        id: undefined,
        productId: 7,
        sku: 'AUS-TRI-400-8',
        variantName: '4.00-8',
        price: 12000,
        specifications: {
          size: '4.00-8',
          plyRating: 8,
          vehicleType: 'Tricycle',
          tubeless: false,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 7,
        sku: 'AUS-TRI-450-12',
        variantName: '4.50-12',
        price: 15000,
        specifications: {
          size: '4.50-12',
          plyRating: 8,
          vehicleType: 'Tricycle',
          tubeless: false,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 8: Hifly Keke NAPEP Tyre
      {
        id: undefined,
        productId: 8,
        sku: 'HIF-KEKE-400-8',
        variantName: '4.00-8',
        price: 11500,
        specifications: {
          size: '4.00-8',
          plyRating: 8,
          vehicleType: 'Tricycle',
          tubeless: false,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 9: Firestone Performer - Agricultural Tyre
      {
        id: undefined,
        productId: 9,
        sku: 'FIR-PERF-18.4-30',
        variantName: '18.4-30',
        price: 180000,
        specifications: {
          size: '18.4-30',
          plyRating: 12,
          vehicleType: 'Tractor',
          application: 'Rear',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 9,
        sku: 'FIR-PERF-11.2-24',
        variantName: '11.2-24',
        price: 120000,
        specifications: {
          size: '11.2-24',
          plyRating: 10,
          vehicleType: 'Tractor',
          application: 'Front',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 10: Dunlop Farm Pro - Agricultural Tyre
      {
        id: undefined,
        productId: 10,
        sku: 'DUN-FARM-16.9-28',
        variantName: '16.9-28',
        price: 155000,
        specifications: {
          size: '16.9-28',
          plyRating: 12,
          vehicleType: 'Tractor',
          application: 'Rear',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 11: Bridgestone Duravis - Light Truck
      {
        id: undefined,
        productId: 11,
        sku: 'BRI-DUR-195-70-15C',
        variantName: '195/70 R15C',
        price: 42000,
        specifications: {
          width: 195,
          aspectRatio: 70,
          rimSize: 15,
          loadIndex: '104/102',
          speedRating: 'R',
          pattern: 'Symmetric',
          vehicleType: 'Light Commercial',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 11,
        sku: 'BRI-DUR-215-75-16C',
        variantName: '215/75 R16C',
        price: 52000,
        specifications: {
          width: 215,
          aspectRatio: 75,
          rimSize: 16,
          loadIndex: '113/111',
          speedRating: 'R',
          pattern: 'Symmetric',
          vehicleType: 'Light Commercial',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 12: Seeman Standard - Car Battery
      {
        id: undefined,
        productId: 12,
        sku: 'SEE-STD-NS40',
        variantName: 'NS40',
        price: 35000,
        specifications: {
          voltage: 12,
          capacity: 35,
          cca: 330,
          dimensions: '197x127x200',
          terminal: 'Top',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 12,
        sku: 'SEE-STD-NS60',
        variantName: 'NS60',
        price: 42000,
        specifications: {
          voltage: 12,
          capacity: 45,
          cca: 430,
          dimensions: '232x173x225',
          terminal: 'Top',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 12,
        sku: 'SEE-STD-N70',
        variantName: 'N70',
        price: 55000,
        specifications: {
          voltage: 12,
          capacity: 70,
          cca: 600,
          dimensions: '306x173x225',
          terminal: 'Top',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 13: Varta Blue Dynamic - Car Battery
      {
        id: undefined,
        productId: 13,
        sku: 'VAR-BD-E11',
        variantName: 'E11 (74Ah)',
        price: 68000,
        specifications: {
          voltage: 12,
          capacity: 74,
          cca: 680,
          dimensions: '278x175x190',
          terminal: 'Top',
          warranty: 24,
          technology: 'EFB',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 13,
        sku: 'VAR-BD-D59',
        variantName: 'D59 (60Ah)',
        price: 58000,
        specifications: {
          voltage: 12,
          capacity: 60,
          cca: 540,
          dimensions: '242x175x190',
          terminal: 'Top',
          warranty: 24,
          technology: 'Standard',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 14: Bosch S4 - Car Battery
      {
        id: undefined,
        productId: 14,
        sku: 'BOS-S4-005',
        variantName: 'S4 005 (60Ah)',
        price: 62000,
        specifications: {
          voltage: 12,
          capacity: 60,
          cca: 540,
          dimensions: '242x175x190',
          terminal: 'Top',
          warranty: 18,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 14,
        sku: 'BOS-S4-007',
        variantName: 'S4 007 (72Ah)',
        price: 72000,
        specifications: {
          voltage: 12,
          capacity: 72,
          cca: 680,
          dimensions: '278x175x190',
          terminal: 'Top',
          warranty: 18,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 15: Solite Silver - Car Battery
      {
        id: undefined,
        productId: 15,
        sku: 'SOL-SIL-65D23L',
        variantName: '65D23L',
        price: 48000,
        specifications: {
          voltage: 12,
          capacity: 60,
          cca: 520,
          dimensions: '232x173x225',
          terminal: 'Top',
          warranty: 18,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 15,
        sku: 'SOL-SIL-75D23L',
        variantName: '75D23L',
        price: 56000,
        specifications: {
          voltage: 12,
          capacity: 65,
          cca: 580,
          dimensions: '232x173x225',
          terminal: 'Top',
          warranty: 18,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 16: Seeman Heavy Duty - Heavy Duty Battery
      {
        id: undefined,
        productId: 16,
        sku: 'SEE-HD-N100',
        variantName: 'N100',
        price: 85000,
        specifications: {
          voltage: 12,
          capacity: 100,
          cca: 800,
          dimensions: '410x176x233',
          terminal: 'Top',
          warranty: 12,
          application: 'Truck',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 16,
        sku: 'SEE-HD-N150',
        variantName: 'N150',
        price: 120000,
        specifications: {
          voltage: 12,
          capacity: 150,
          cca: 1000,
          dimensions: '508x222x238',
          terminal: 'Top',
          warranty: 12,
          application: 'Heavy Truck',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 17: Varta Promotive Black - Heavy Duty Battery
      {
        id: undefined,
        productId: 17,
        sku: 'VAR-PB-J1',
        variantName: 'J1 (125Ah)',
        price: 145000,
        specifications: {
          voltage: 12,
          capacity: 125,
          cca: 900,
          dimensions: '354x174x190',
          terminal: 'Top',
          warranty: 24,
          application: 'Commercial Vehicle',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 18: Solite Bike - Motorcycle Battery
      {
        id: undefined,
        productId: 18,
        sku: 'SOL-BIKE-YTX7A',
        variantName: 'YTX7A-BS',
        price: 12000,
        specifications: {
          voltage: 12,
          capacity: 6,
          cca: 100,
          dimensions: '150x87x94',
          terminal: 'Top',
          warranty: 6,
          type: 'AGM',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 18,
        sku: 'SOL-BIKE-YTX9',
        variantName: 'YTX9-BS',
        price: 15000,
        specifications: {
          voltage: 12,
          capacity: 8,
          cca: 120,
          dimensions: '150x87x105',
          terminal: 'Top',
          warranty: 6,
          type: 'AGM',
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 19: Sachs Shock Absorber
      {
        id: undefined,
        productId: 19,
        sku: 'SAC-SHOCK-TOY-CAM',
        variantName: 'Toyota Camry Front',
        price: 28000,
        specifications: {
          vehicle: 'Toyota Camry 2007-2011',
          position: 'Front',
          type: 'Gas',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 19,
        sku: 'SAC-SHOCK-HON-ACC',
        variantName: 'Honda Accord Rear',
        price: 32000,
        specifications: {
          vehicle: 'Honda Accord 2008-2012',
          position: 'Rear',
          type: 'Gas',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 20: Monroe OESpectrum
      {
        id: undefined,
        productId: 20,
        sku: 'MON-OE-TOY-COR',
        variantName: 'Toyota Corolla Front',
        price: 25000,
        specifications: {
          vehicle: 'Toyota Corolla 2009-2013',
          position: 'Front',
          type: 'Gas',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 21: TRW Tie Rod End
      {
        id: undefined,
        productId: 21,
        sku: 'TRW-TIE-TOY-CAM-L',
        variantName: 'Toyota Camry Left',
        price: 8500,
        specifications: {
          vehicle: 'Toyota Camry 2007-2011',
          position: 'Left',
          thread: 'M14x1.5',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 21,
        sku: 'TRW-TIE-TOY-CAM-R',
        variantName: 'Toyota Camry Right',
        price: 8500,
        specifications: {
          vehicle: 'Toyota Camry 2007-2011',
          position: 'Right',
          thread: 'M14x1.5',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 22: Lemforder Ball Joint
      {
        id: undefined,
        productId: 22,
        sku: 'LEM-BALL-MERC-W204-L',
        variantName: 'Mercedes W204 Lower Left',
        price: 18000,
        specifications: {
          vehicle: 'Mercedes C-Class W204',
          position: 'Lower Left',
          diameter: '18mm',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 23: TRW Steering Rack End
      {
        id: undefined,
        productId: 23,
        sku: 'TRW-RACK-HON-CIV-L',
        variantName: 'Honda Civic Left',
        price: 12000,
        specifications: {
          vehicle: 'Honda Civic 2006-2011',
          position: 'Left',
          thread: 'M12x1.25',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Product 24: TRW Brake Pad
      {
        id: undefined,
        productId: 24,
        sku: 'TRW-PAD-TOY-CAM-F',
        variantName: 'Toyota Camry Front',
        price: 15000,
        specifications: {
          vehicle: 'Toyota Camry 2007-2011',
          position: 'Front',
          material: 'Ceramic',
          quantity: '4 pads',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: undefined,
        productId: 24,
        sku: 'TRW-PAD-TOY-COR-F',
        variantName: 'Toyota Corolla Front',
        price: 12000,
        specifications: {
          vehicle: 'Toyota Corolla 2009-2013',
          position: 'Front',
          material: 'Semi-Metallic',
          quantity: '4 pads',
          warranty: 12,
        },
        createdBy: ActorType.SYSTEM_ACTOR,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    for (const variantData of defaultVariants) {
      const variant = new ProductVariant(
        variantData.id,
        variantData.productId,
        variantData.sku,
        variantData.variantName,
        variantData.price,
        variantData.specifications,
        variantData.createdBy,
        variantData.createdAt,
        variantData.updatedAt,
      );
      await this.variants.commit(variant);
    }

    console.log('Default product variants seeded successfully');
  }
}
