enum ActivityType {
  SALE_CREATED = 'SALE_CREATED',
  SALE_CANCELLED = 'SALE_CANCELLED',
  PAYMENT_RECORDED = 'PAYMENT_RECORDED',
  INVENTORY_ADJUSTED = 'INVENTORY_ADJUSTED',
  INVENTORY_TRANSFERRED = 'INVENTORY_TRANSFERRED',
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  BRANCH_CREATED = 'BRANCH_CREATED',
  WAREHOUSE_CREATED = 'WAREHOUSE_CREATED',
  CUSTOMER_CREATED = 'CUSTOMER_CREATED',
  STAFF_REGISTERED = 'STAFF_REGISTERED',
  SUPPLY_CREATED = 'SUPPLY_CREATED',
  SUPPLY_FULFILLED = 'SUPPLY_FULFILLED',
  STAFF_TRANSFERRED = 'STAFF_TRANSFERRED',
  EXPENSE_RECORDED = 'EXPENSE_RECORDED',
}

export default ActivityType;
